project:
  type: website
  output-dir: .

website:
  title: "Nayla Sol Garcilazo"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: codigo.qmd
        text: Cs. Sociales Computacionales
      - href: docencia.qmd
        text: Docencia
      - href: encuestas.qmd
        text: Encuestas



    right:
      - text: "EN 🌐"
        href: "https://naylasolg.github.io/Site_En/"
        target: _blank
      - text: "Contacto"
        menu: 
          - text: "Email"
            href: mailto:ngarcilazo@unsam.edu.ar
          - text: "LinkedIn"
            href: https://www.linkedin.com/in/nayla-sol-garcilazo/
            target: _blank
format:
  html:
    theme: minty